# Generated by Django 5.2 on 2025-05-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_profile_image_profile_age_profile_allergies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verified',
        ),
    ]
