# Generated by Django 5.0.2 on 2025-05-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_profile_bio_remove_profile_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='allergies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dietary_preferences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='medical_conditions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
