# Generated by Django 5.0.2 on 2025-05-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_profile_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('low', 'Düşük'), ('moderate', 'Orta'), ('high', 'Yüksek')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='health_goals',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
